name: CI - Backend Congreso

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 1. Clonar repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurar Node (ajusta versión si usas otra)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Instalar dependencias
      - name: install dependencies
        run: npm ci

      # 4. Verificar lint
      - name: lint
        run: npm run lint

      # 5. Verificar build de TypeScript
      - name: build
        run: npm run build
